name: adl_vod_encoder_nov2
channels:
  - defaults
#  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - dask
  - pytorch
#  - torchvision
#  - torchaudio
  - pytorch-cuda
  - pytorch-lightning
  - setuptools=59.5.0
  - torchvision
  - pip
  - pip:
      - scikit-learn
      - smecv_grid
      - SimpleCRF
      - kmeans-pytorch
      - pynetcf
      - eofs