name: adl_vod_encoder_nov5
channels:
  - defaults
#  - anaconda
#  - conda-forge
#  - pytorch
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - dask
#  - pytorch
#  - torchvision
#  - torchaudio
#  - pytorch-cuda::nvidia
#  - pytorch-lightning
#  - setuptools=59.5.0
  - setuptools
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - pytorch-lightning
      - scikit-learn
      - smecv_grid
      - SimpleCRF
      - kmeans-pytorch
#      - pynetcf
      - eofs