name: adl_vod_encoder11
channels:
#  - defaults
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - dask
  - pytorch=1.10
  - pytorch-lightning
#  - torchvision
#  - torchaudio
#  - cudatoolkit
  - pip
  - pip:
      - sklearn
      - smecv_grid
#      - SimpleCRF
#      - kmeans-pytorch
      - pynetcf
#      - eofs
#      - audtorch
#      - pyro-ppl
#      - gpytorch